language: julia
julia:
  - nightly
  - 0.6
os:
  - linux
  - osx
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true

notifications:
  email: false
script:
  - make -j3
  - julia test.jl
jobs:
  include:
    - stage: deploy
      if: tag IS present
      julia: 0.6
      sudo: required
      before_script:
        - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
        - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
      script:
        - julia build_tarballs.jl
      deploy:
          provider: releases
          api_key:
              # Note; this api_key is only valid for JuliaStats/Rmath-julia; you need
              # to make your own: https://docs.travis-ci.com/user/deployment/releases/
              secure: WptNvHrgro4HgxaM+0qRdMxktoo15TQe7iqVNynBlvaWgUiGxy6WB9sOGosfRy/wHwfpOI7uYgfzbmHLxuponrWdubUutq6K2zf9ThHLDpjNdS+kglXIA3DLlQiwaIeWQ9LQHeQS9jku++PIFAyWEXpPQ9wzOTYb3LhKwhX4kRs=
          file_glob: true
          file: products/*
          skip_cleanup: true
          on:
              repo: JuliaStats/Rmath-julia
              tags: true
